parameters:
#    triangulum_website.example.class: Triangulum\WebsiteBundle\Example

services:
#    triangulum_website.example:
#        class: %triangulum_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
