parameters:
#    triangulum_website.example.class: Triangulum\WebsiteBundle\Example

services:
    twig.extension:
        class: Triangulum\WebsiteBundle\Extension\TriangulumTwigExtension
        tags:
            -  { name: twig.extension }

    controller_helper:
        class: Triangulum\WebsiteBundle\Helper\ControllerHelper
        arguments:
            config: %config%
            translator: @translator
            mailer: @mailer
            templating: @templating
            security: @security.context